### ISSUE TITLE
Avoid overeager querying on edit post screen

### ISSUE THREAD

**Issue by jeremyfelt** [richardtape/content-visibility#7]
The [query used to populate data](https://github.com/richardtape/content-visibility/blob/1a554a5a82dfee49d7a407a8ab5e126c967fe1c9/includes/content-visibility.php#L209-L212) for the [post page inserter](https://github.com/richardtape/content-visibility/blob/1a554a5a82dfee49d7a407a8ab5e126c967fe1c9/src/controls/special-page/content-visibility-post-page-inserter.js#L19) can be pretty expensive on sites with many posts.

I _think_ the intention is for this feature to only be used on the widgets screen, where a block can be restricted to specific pages/posts, but the query is currently loading on all post editor screens as well—where the data seems to be unused. The solution to this may be as straight forward as returning an empty array when not on the widget screen.

**Comment by richardtape** [comment]
Yikes! Nice spot. Thanks for reporting this. This is definitely a bug. That component isn't meant to be loaded on any of the content type edit screens.

I do have [a conditional check](https://github.com/richardtape/content-visibility/blob/master/src/controls/special-page/content-visibility-special-page-controls.js#L52) as to when those components should be loaded, but that's clearly not doing what I intend it to be doing.

Will take a look into this.

**Comment by richardtape** [comment]
Stopped that data being loaded where is shouldn't be which closes this issue. That's now released as 0.2.1.

I'm going to open another issue with regards to these queries potentially loading a whole chunk of data when perhaps that might not be necessary on sites with large amounts of content.

Thanks again for raising this issue.
